# LAMMPS 2005 MD Simulation Parameters - Generated by XenoView
# Structure file "C:\Users\Steven\Desktop\LAMMPS_Science_Simulation\ddt_me_100.lmp"
# Source force field file pcff_d.frc

units		real
atom_style	full

pair_style	hybrid/overlay lj/cut 10 morse 10 hbond/dreiding/lj 4 9.0 11.0 90
bond_style      class2
angle_style     class2
dihedral_style  class2

read_data	addmolecule_184_rand.lmp

pair_coeff	1	1	lj/cut	0.039	2.935
pair_coeff	2	2	lj/cut	0.118	3.905
pair_coeff	3	3	lj/cut	0.175	3.905
pair_coeff	4	4	lj/cut	0.39743	4.25
pair_coeff	5	5	lj/cut	0.2	2.85
pair_coeff	5	5	hbond/dreiding/lj 6 i 5.0 2.850 4
pair_coeff	6	6	lj/cut	0	1.78

pair_coeff	1	2	lj/cut	0.067838042	3.42
pair_coeff	1	3	lj/cut	0.082613558	3.42
#pair_coeff	1	4	lj/cut	0.124498072	3.5925
pair_coeff	1	5	lj/cut	0.088317609	2.8925
pair_coeff	1	6	lj/cut	0	2.3575
pair_coeff	2	3	lj/cut	0.143701079	3.905
pair_coeff	2	4	lj/cut	0.216556552	4.0775
pair_coeff	2	5	lj/cut	0.153622915	3.3775
pair_coeff	2	6	lj/cut	0	2.8425
pair_coeff	3	4	lj/cut	0.263723814	4.0775
pair_coeff	3	5	lj/cut	0.187082869	3.3775
pair_coeff	3	6	lj/cut	0	2.8425
pair_coeff	4	5	lj/cut	0.281932616	3.55
pair_coeff	4	6	lj/cut	0	3.015
pair_coeff	5	6	lj/cut	0	2.315


pair_coeff 1 4 morse 5.58 0.746 2.868

#neighbor	1 bin
neigh_modify	delay 5

#comm_modify cutoff 14

timestep	0.5

group crystal type 1
group adsorbate type 2 3 4 5 6

#compute GYR adsorbate gyration/molecule
#compute MMSD adsorbate msd/molecule
compute PE all pe
#compute KE all ke


#fix 3 adsorbate ave/time 100 1 100 c_GYR file gyr.out mode vector
#fix 4 adsorbate ave/time 100 1 100 c_MMSD[4] file mmsd.out mode vector 
fix 5 all ave/time 100 1 100 c_PE file pe.out mode scalar
#fix 6 all ave/time 100 1 100 c_KE file ke.out mode scalar


thermo_style	custom step etotal ke temp pe ebond eangle edihed eimp evdwl ecoul elong press
thermo	10

compute myTemp adsorbate temp

thermo_modify temp myTemp

fix 1 adsorbate nvt temp 298 298 10 
fix 2 crystal setforce 0.0 0.0 0.0

dump 2 all xyz 100 ddt_me_200.xyz

#minimize 1.0e-4 1.0e-6 100 1000

run	 0

write_data ddt_me_relax.temp
